### PR TITLE
Fix missing includes and have docker reference local repo

### PR DESCRIPTION
**Pull request by csanders-git**
Some includes were oddly missing within a bunch of files.
However, while this will allow it to compile, we still fail two tests -- not sure what these tesets are about.

```

      Start 31: blackbox_ruleset
31/33 Test #31: blackbox_ruleset .................***Failed    0.40 sec
      Start 32: blackbox_rules
32/33 Test #32: blackbox_rules ...................   Passed    3.15 sec
      Start 33: blackbox_instances
33/33 Test #33: blackbox_instances ...............***Failed    0.87 sec

94% tests passed, 2 tests failed out of 33
```

### CODE REVIEW

**Comment by csanders-git** [comment]
We'll need this dockerfile working in order for us to run CRS tests against this :)

**Comment by tinselcity** [comment]
Thx I'll test this out locally first.

**Comment by csanders-git** [comment]
How goes this testing? We'd love to get this building so we can start running CRS testing against this (even if it is failing)

**Comment by tinselcity** [comment]
Seems okay I get the same test failures:
```sh
Running tests...
Test project /opt/waflz/build
      Start  1: file_util
 1/33 Test  #1: file_util ........................   Passed    0.00 sec
      Start  2: string_util
 2/33 Test  #2: string_util ......................   Passed    0.00 sec
      Start  3: time_util
 3/33 Test  #3: time_util ........................   Passed    0.12 sec
      Start  4: geoip2_mmdb
 4/33 Test  #4: geoip2_mmdb ......................   Passed    0.01 sec
      Start  5: regex
 5/33 Test  #5: regex ............................   Passed    0.01 sec
      Start  6: md5
 6/33 Test  #6: md5 ..............................   Passed    0.00 sec
      Start  7: jspb
 7/33 Test  #7: jspb .............................   Passed    0.00 sec
      Start  8: instances
 8/33 Test  #8: instances ........................   Passed    0.01 sec
      Start  9: matched_data
 9/33 Test  #9: matched_data .....................   Passed    0.00 sec
      Start 10: profile_acl
10/33 Test #10: profile_acl ......................   Passed    0.11 sec
      Start 11: profile_policies
11/33 Test #11: profile_policies .................   Passed    0.01 sec
      Start 12: shell_shock
12/33 Test #12: shell_shock ......................   Passed    0.00 sec
      Start 13: decode
13/33 Test #13: decode ...........................   Passed    0.00 sec
      Start 14: op
14/33 Test #14: op ...............................   Passed    0.01 sec
      Start 15: var
15/33 Test #15: var ..............................   Passed    0.01 sec
      Start 16: tx
16/33 Test #16: tx ...............................   Passed    0.00 sec
      Start 17: render
17/33 Test #17: render ...........................   Passed    0.00 sec
      Start 18: nms
18/33 Test #18: nms ..............................   Passed    0.00 sec
      Start 19: ac
19/33 Test #19: ac ...............................   Passed    0.00 sec
      Start 20: byte_range
20/33 Test #20: byte_range .......................   Passed    0.00 sec
      Start 21: luhn
21/33 Test #21: luhn .............................   Passed    0.00 sec
      Start 22: parser_json
22/33 Test #22: parser_json ......................   Passed    0.00 sec
      Start 23: kycb_db
23/33 Test #23: kycb_db ..........................   Passed    1.20 sec
      Start 24: rl_op
24/33 Test #24: rl_op ............................   Passed    0.01 sec
      Start 25: challenge
25/33 Test #25: challenge ........................   Passed    0.11 sec
      Start 26: enforcer
26/33 Test #26: enforcer .........................   Passed    3.11 sec
      Start 27: config
27/33 Test #27: config ...........................   Passed    9.12 sec
      Start 28: config_bc
28/33 Test #28: config_bc ........................   Passed    6.95 sec
      Start 29: integration
29/33 Test #29: integration ......................   Passed    2.11 sec
      Start 30: blackbox_access_settings
30/33 Test #30: blackbox_access_settings .........***Failed    0.60 sec
      Start 31: blackbox_ruleset
31/33 Test #31: blackbox_ruleset .................***Failed    0.42 sec
      Start 32: blackbox_rules
32/33 Test #32: blackbox_rules ...................***Failed    0.56 sec
      Start 33: blackbox_instances
33/33 Test #33: blackbox_instances ...............***Failed    0.56 sec

88% tests passed, 4 tests failed out of 33

Total Test time (real) =  25.07 sec

The following tests FAILED:
	 30 - blackbox_access_settings (Failed)
	 31 - blackbox_ruleset (Failed)
	 32 - blackbox_rules (Failed)
	 33 - blackbox_instances (Failed)
```

I'll have to look into why.  The blackbox tests bring up a standalone http server running the waf engine listening on port 12345.

**Comment by tinselcity** [comment]
Found the issue -has to do with our "test fixtures"

```sh
root@bf8967bdc8eb:/opt/waflz/build# ctest -R blackbox_ruleset                
Test project /opt/waflz/build
    Start 31: blackbox_ruleset
1/1 Test #31: blackbox_ruleset .................***Failed    0.36 sec

0% tests passed, 1 tests failed out of 1

Total Test time (real) =   0.36 sec

The following tests FAILED:
	 31 - blackbox_ruleset (Failed)
Errors while running CTest
root@bf8967bdc8eb:/opt/waflz/build# env CTEST_OUTPUT_ON_FAILURE=1 ctest -R blackbox_ruleset                             
Test project /opt/waflz/build
    Start 31: blackbox_ruleset
1/1 Test #31: blackbox_ruleset .................***Failed    0.36 sec
============================= test session starts ==============================
platform linux2 -- Python 2.7.12, pytest-4.5.0, py-1.8.0, pluggy-0.12.0 -- /usr/bin/python
cachedir: .pytest_cache
rootdir: /opt/waflz/tests/blackbox, inifile: pytest.ini
plugins: sugar-0.9.2
collecting ... collected 4 items

../../../tests/blackbox/ruleset/test_ruleset.py::test_OWASP_2_2_9_anomaly ERROR [ 25%]
../../../tests/blackbox/ruleset/test_ruleset.py::test_OWASP_2_2_9_anomaly_low ERROR [ 50%]
../../../tests/blackbox/ruleset/test_ruleset.py::test_OWASP_3_2_anomaly ERROR [ 75%]
../../../tests/blackbox/ruleset/test_ruleset.py::test_OWASP_3_2_anomaly_low ERROR [100%]

==================================== ERRORS ====================================
__________________ ERROR at setup of test_OWASP_2_2_9_anomaly __________________
Fixture "setup_func" called directly. Fixtures are not meant to be called directly,
but are created automatically when test functions request them as parameters.
See https://docs.pytest.org/en/latest/fixture.html for more information about fixtures, and
https://docs.pytest.org/en/latest/deprecations.html#calling-fixtures-directly about how to update your code.
________________ ERROR at setup of test_OWASP_2_2_9_anomaly_low ________________
Fixture "setup_func" called directly. Fixtures are not meant to be called directly,
but are created automatically when test functions request them as parameters.
See https://docs.pytest.org/en/latest/fixture.html for more information about fixtures, and
https://docs.pytest.org/en/latest/deprecations.html#calling-fixtures-directly about how to update your code.
___________________ ERROR at setup of test_OWASP_3_2_anomaly ___________________
Fixture "setup_func" called directly. Fixtures are not meant to be called directly,
but are created automatically when test functions request them as parameters.
See https://docs.pytest.org/en/latest/fixture.html for more information about fixtures, and
https://docs.pytest.org/en/latest/deprecations.html#calling-fixtures-directly about how to update your code.
_________________ ERROR at setup of test_OWASP_3_2_anomaly_low _________________
Fixture "setup_func" called directly. Fixtures are not meant to be called directly,
but are created automatically when test functions request them as parameters.
See https://docs.pytest.org/en/latest/fixture.html for more information about fixtures, and
https://docs.pytest.org/en/latest/deprecations.html#calling-fixtures-directly about how to update your code.
=========================== 4 error in 0.02 seconds ============================

```

I'll work on fixing these -apparently calling them this way is deprecated in pytest 4.x.

**Comment by csanders-git** [comment]
dammit pytest. Well let me know if you need any help with that -- also please do feel free to ping me when you get it and i'll add these to our tests -- even if they fail.

**Comment by tinselcity** [comment]
@csanders-git FYI seems to be fixed locally for me with docker with this [PR](https://github.com/VerizonDigital/waflz/pull/59)

Let me know if you still get issues

**Comment by tinselcity** [comment]
Yeah sorry for the delay -believe it or not I’m trying to come up to speed
a bit on Docker.  I’ll do this today.  Thanks so much for help here -I’ve
followed your work at Trustwave and on Modsecurity, and really appreciate
having a big name in the community checking out our stuff.

Thanks,
Reed

**Pull request merged**
