### PR TITLE
Changing the docker CMD

### PR DESCRIPTION
**Pull request by csanders-git**
This seems to work pretty well. 

A couple notes, the suggestion to make a bogus max mind didn't seem to work, I needed to provide. Also, i'm not sure how to really use the `--modsecurity` flag in bulk :), otherwise i'll need to convert the CRS 3.x rules to the JSON format, not sure if you guys have a tool for that (maybe waflz_dump). Great work!

```
docker build -t waflz .
docker run --rm -p80:12345 -it waflz 
```

### CODE REVIEW

**Comment by csanders-git** [comment]
Actually looks like `waflz_dump` works well. Made this little script - haven't tested it yet with a new profile.

```
import os
import subprocess
import sys

#git clone https://github.com/SpiderLabs/owasp-modsecurity-crs /opt/owasp-modsecurity-crs
start_folder="/opt/owasp-modsecurity-crs/rules/"
command="/opt/waflz/build/util/waflz_dump/waflz_dump --input={0} --json"
output_location = "/opt/owasp-modsecurity-crs/version/v3.2-dev/policy/"
for filename in os.listdir(start_folder):
        if filename[-5:] == ".conf":
                full_file_path = start_folder + filename
                command = command.format(full_file_path)
                split_cmd = command.split(' ')
                p = subprocess.Popen(split_cmd, stdout=subprocess.PIPE)
                json_out = p.communicate()[0]
                f = open(output_location+filename + ".json", 'w')
                f.write(str(json_out))
                f.close()
```

**Comment by csanders-git** [comment]
Just if interested, this is my fork with CRS 3.2. For some reason the rules currently aren't firing but that is a problem for later in the day to figure out. `waflz_dump` seemed to work well for converting them to JSON and I made my own custom policy that includes the JSON rules.

https://github.com/csanders-git/waflz/tree/custom_docker

**Comment by tinselcity** [comment]
I think I know why.  It looks like upstream they've removed the `tx.msg` bits from every rule.  For example looking at one guy I see something like:
```diff
SecRule REQUEST_HEADERS:Connection "@rx \b(?:keep-alive|close),\s?(?:keep-alive|close)\b" \
    "id:920210,\
    phase:2,\
    block,\
    t:none,\
    msg:'Multiple/Conflicting Connection Header Data Found.',\
    logdata:'%{matched_var}',\
    tag:'application-multi',\
    tag:'language-multi',\
    tag:'platform-multi',\
    tag:'attack-protocol',\
    tag:'OWASP_CRS/PROTOCOL_VIOLATION/INVALID_HREQ',\
    ver:'OWASP_CRS/3.1.0',\
    severity:'WARNING',\
-   setvar:'tx.msg=%{rule.msg}',\
    setvar:'tx.anomaly_score_pl1=+%{tx.warning_anomaly_score}',\
-   setvar:'tx.%{rule.id}-OWASP_CRS/PROTOCOL_VIOLATION/INVALID_HREQ-%{matched_var_name}=%{matched_var}'"

```

I get that it's redundant, but I guess we had some builtin assumptions about that existing in our engine in order for a rule to trip -that is we wouldn't trip on rules sans description of why they tripped in the `tx.msg` field.  I can look at adjusting our engine to use either the top-level `msg` field or if that doesn't exist maybe dropping back to the `tx.msg`.

**Comment by csanders-git** [comment]
ahh interesting!!! we removed it recently too because we thought no one was using it! @dune73

**Comment by tinselcity** [comment]
I was wrong.  It was the ruleset detection we use to detect and run the native anomaly scoring inside of the engine.  It was broken for v3.x rules with paranoia level mode scoring like `tx.anomaly_score_pl1=+...`.  [I tried to fix the detection](https://github.com/VerizonDigital/waflz/commit/257d9aa773f7090ba4021f8d44a45aeed8ddc4af) -it's a [pretty fuzzy detection](https://github.com/VerizonDigital/waflz/blob/master/util/waflz_server/sx_modsecurity.cc#L104) -just searching for things the _look_ like an OWASP 3.x ruleset so it can flip to 3.x anomaly scoring internally.

Here's an example conf you can run btw:
`rules.conf`
```sh
  SecRule &REQUEST_HEADERS:Host "@eq 0" \
        "phase:2,\
        rev:'2',\
        ver:'OWASP_CRS/3.1.0',\
        t:none,block,\
        msg:'Request Missing a Host Header',\
        id:'960008',\
        severity:'4',\
        setvar:tx.anomaly_score_pl1=+%{tx.warning_anomaly_score}

  SecRule REQUEST_HEADERS:User-Agent "@contains monkeez" \
        "phase:2,\
        rev:'2',\
        ver:'OWASP_CRS/3.1.0',\
        t:none,block,\
        msg:'Request User-Agent is monkeez',\
        id:'960008',\
        severity:'4',\
        setvar:tx.anomaly_score_pl1=+%{tx.warning_anomaly_score}
```
And then:
```sh
waflz_server --modsecurity=rule.conf
```

Then in another terminal
```sh
>curl -s 'localhost:12345/test.html' -H'User-Agent: monkeez' | jq '.'
{
  "rule_msg": "Inbound Anomaly Score Exceeded (Total Score: 3): Last Matched Message: ",
  "rule_target": [
    {
      "name": "TX",
      "param": "ANOMALY_SCORE"
    }
  ],
  "rule_op_name": "gt",
  "rule_op_param": "0",
  "rule_tag": [
    "OWASP_CRS/ANOMALY/EXCEEDED"
  ],
  "matched_var": {
    "name": "REQUEST_HEADERS:User-Agent",
    "value": "bW9ua2Vleg=="
  },
  "total_anomaly_score": 3,
  "sub_event": [
    {
      "rule_id": 960008,
      "rule_msg": "Request User-Agent is monkeez",
      "rule_intercept_status": 403,
      "rule_target": [
        {
          "name": "REQUEST_HEADERS",
          "param": "User-Agent"
        }
      ],
      "rule_op_name": "CONTAINS",
      "rule_op_param": "monkeez",
      "matched_var": {
        "name": "REQUEST_HEADERS:User-Agent",
        "value": "bW9ua2Vleg=="
      },
      "total_anomaly_score": 3,
      "waf_profile_id": "NA",
      "waf_profile_name": "NA"
    }
  ],
  "waf_profile_id": "NA",
  "waf_profile_name": "NA"
}
```

I'm aware of the geoipdb errors if none provided -I'll work on fixing soon.

BTW the reason we haven't noticed this is because we run the rulesets in a more _managed_ mode with our [profile configuration](https://verizondigital.github.io/waflz/profiles.html).

**Review by tinselcity — APPROVED** [review]
looks fine.

**Pull request merged**
